# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Ruoxuan Li"                                # Your name
  description: "Ruoxuan Li is a current second-year PhD student working under Dr. Mark Jackson's laboratory."   # A brief slogan (optional)
  image: img/RL.jpg
  
  favicon: img/cat.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/cat.png
    
    # your sub-pages
    left:
      - text: "Education"
        href: education/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "My Life"
        href: life/index.qmd
    
    # your social media handles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ruoxuan-li-b9870422a/
      - icon: envelope
        aria-label: email
        href: "mailto:rxl884@case.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true